preload = $HOME/.config/hypr/img/bg/mices.png
preload = $HOME/.config/hypr/img/bg/japanNight.png
preload = $HOME/.config/hypr/img/bg/akihabara_night.png

wallpaper = ,$HOME/.config/hypr/img/bg/akihabara_night.png
