local home = os.getenv("HOME")

return {
  "nvimdev/dashboard-nvim",
  dependencies = {
    "nvim-tree/nvim-web-devicons",
  },
  event = "VimEnter",
  opts = {
    theme = "doom",
    config = {
      center = {
        {
          icon = "  ",
          desc = "[O]ld Files                          ",
          action = "Telescope oldfiles",
          key = "o",
          icon_hl = "Title",
          desc_hl = "String",
          key_hl = "Number",
        },
        {
          icon = "󰱼  ",
          desc = "[F]ind Files                         ",
          action = "Telescope find_files",
          key = "f",
          icon_hl = "Title",
          desc_hl = "String",
          key_hl = "Number",
        },
        {
          icon = "󰥨  ",
          desc = "[P]roject                            ",
          action = ":lua require('telescope').extensions.project.project({ display_type = 'full'  })",
          key = "p",
          icon_hl = "Title",
          desc_hl = "String",
          key_hl = "Number",
        },
        {
          icon = "  ",
          desc = "[G]rep                               ",
          action = "Telescope live_grep",
          key = "g",
          icon_hl = "Title",
          desc_hl = "String",
          key_hl = "Number",
        },
        {
          icon = "  ",
          desc = "Open [H]ere                           ",
          action = ":e .",
          key = "h",
          icon_hl = "Title",
          desc_hl = "String",
          key_hl = "Number",
        },
        {
          icon = "  ",
          desc = "[S]cratch File                      ",
          action = ":Scratch",
          key = "s",
          icon_hl = "Title",
          desc_hl = "String",
          key_hl = "Number",
        },
        {
          icon = "  ",
          desc = "[E]dit Dotfiles                     ",
          action = ":e $HOME/Documents/dotfiles/",
          key = "e",
          icon_hl = "Title",
          desc_hl = "String",
          key_hl = "Number",
        },
      },
    },
    preview = {
      command = "lolcat",
      file_path = home .. "/.config/nvim/dashboard.txt",
      file_height = 10,
      file_width = 43,
    },
  },
}
