return {
  {
    "lbrayner/vim-rzip", -- yarn pnp
    lazy = false,
  },
  {
    "LintaoAmons/scratch.nvim",
    dependencies = { "nvim-telescope/telescope.nvim" },
    cmd = { "Scratch", "ScratchWithName", "ScratchOpen", "ScratchOpenFzf" },
    opts = {
      file_picker = "telescope",
      filetypes = { "txt", "js", "ts", "javascriptreact", "typescriptreact", "md", "json", "yaml", "sh" },
    },
  },
  {
    "nvim-lualine/lualine.nvim",
    opts = { options = { theme = "nord" } },
  },
  {
    "famiu/bufdelete.nvim",
    keys = {
      { "<C-w>", "<CMD>Bdelete<CR>", desc = "Close current buffer" },
    },
  },
  {
    "windwp/nvim-autopairs",
    event = "InsertEnter",
    opts = { disable_filetype = { "TelescopePrompt", "vim" } },
  },
  {
    "mg979/vim-visual-multi",
    init = function()
      vim.g.VM_default_mappings = 0
    end,
    keys = {
      { "<C-d>", "<Plug>(VM-Find-Under)", mode = { "n", "v" }, desc = "Multi cursor editing" },
      { "<C-d>", "<Plug>(VM-Find-Subword-Under)", mode = { "x" }, desc = "Multi cursor editing" },
    },
  },
  {
    "folke/todo-comments.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    event = { "BufReadPre", "BufNewFile" },
    cmd = { "TodoTelescope" },
    config = function(_, opts)
      require("todo-comments").setup(opts)

      vim.api.nvim_del_user_command("TodoFzfLua")
      vim.api.nvim_del_user_command("TodoTrouble")
    end,
  },

  { "JoosepAlviste/nvim-ts-context-commentstring" }, -- TODO: add commenting plugin

  {
    "dmmulroy/tsc.nvim",
    cmd = { "TSC" },
    config = function()
      -- Yarn PnP projects have no `node_modules/.bin`, so tsc.nvim's default
      -- lookup never finds a binary. Fall back to the SDK shim generated by
      -- `yarn dlx @yarnpkg/sdks base` (or `vscode`), which wraps `tsc` with
      -- the PnP loader and is a real executable file on disk.
      local tsc_utils = require("tsc.utils")
      local find_tsc_bin = tsc_utils.find_tsc_bin

      tsc_utils.find_tsc_bin = function(bin_name)
        bin_name = bin_name or "tsc"

        local pnp_bin = vim.fn.findfile(".yarn/sdks/typescript/bin/" .. bin_name, ".;")
        if pnp_bin ~= "" then
          return pnp_bin
        end

        return find_tsc_bin(bin_name)
      end

      require("tsc").setup({})
    end,
  },
}
