#!/bin/sh

# OG prompt
# PROMPT="%B%{$fg[blue]%}[%{$fg[green]%}%n%{$fg[green]%}@%{$fg[green]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )%{$fg[cyan]%}%c%{$reset_color%} "


# Prompt with user@hostname
# PROMPT="
# %B%{$fg[blue]%}╭─[%{$fg[green]%}%n@%m%{$fg[blue]%}]-%{$fg[blue]%}[%{$fg[green]%}%~%{$fg[blue]%}]%{$reset_color%}\$vcs_info_msg_0_
# %B%{$fg[blue]%}╰──╼ %{$reset_color%}"

# Prompt with user
# PROMPT="
# %B%{$fg[blue]%}╭─[%{$fg[green]%}%n%{$fg[blue]%}]-%{$fg[blue]%}[%{$fg[green]%}%~%{$fg[blue]%}]%{$reset_color%}\$vcs_info_msg_0_
# %B%{$fg[blue]%}╰──╼ %{$reset_color%}"


# Prompt without user@hostname
PROMPT="
%B%{$fg[blue]%}╭─%{$fg[blue]%}[%{$fg[green]%}%~%{$fg[blue]%}]%{$reset_color%}
%B%{$fg[blue]%}╰──%(?:%{$fg[blue]%}╼:%{$fg[red]%}╼) %{$reset_color%}"
